// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Todo struct {
	ID        int32
	Title     string
	Status    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
